### ISSUE TITLE
Pagination and current query addition

### ISSUE THREAD

**Issue by bdsoha** [jedrzej/pimpable#4]
Have you every thought of implementing helper functions to find out which conditions are already being applied in the query string. 
When I try to use pagination and multiple filters I end up mistakenly overriding old filters from the query string.

```php
function isPimpable(Model $model)
{
    return isSortable($model) || isWithable($model) || isSearchable($model);
}

function isSortable(Model $model)
{
    return array_intersect(
        [Jedrzej\Sortable\SortableTrait::class],
        class_uses($model))
        ? true : false;
}

function isWithable(Model $model)
{
    return array_intersect(
        [Jedrzej\Withable\WithableTrait::class],
        class_uses($model))
        ? true : false;
}

function isSearchable(Model $model)
{
    return array_intersect(
        [Jedrzej\Searchable\SearchableTrait::class],
        class_uses($model))
        ? true : false;
}
```

There can be addiotnal function to actually track down the current status and just append new ones, or remove old ones.

```php
function getSortable()
{
    /** @TODO: get the proper 'sort' parameter name */
    return ['sort' => Request::query('sort')];
}

function getSearchable(Model $model)
{
    $searchable = [];

    if (method_exists($model, 'getSearchableAttributes')) {
        $searchable = $model->getSearchableAttributes();
    }

    if (property_exists($model, 'searchable')) {
        $searchable = $model->searchable;
    }

    return array_intersect(array_keys(Request::query()), $searchable);
}
```

**Comment by jedrzej** [comment]
Hey, thank you for your feedback, unfortunately I'm a bit lost reading your post. How the "isPimpable/Searchable/..." methods you posted are related to what you mention in the first paragraph: "which conditions are already being applied in the query string"?

I'm also not sure what those "getSortable/getSearchable" methods are supposed to do. First of all they're a bit inconsistent - one takes model as an argument, second does not. One returns an array that contains one value that should be used for sorting, second returns just names of fields that should be used for searching.

What's the use case here? How do you intend to use those methods? What is it that you're trying to achieve with them? It will help me understand the idea behind them.

**Comment by bdsoha** [comment]
Im sorry for the rambling, I simply had many different ideas going on in my head and didn't sort them through properly.

There are many situations when I would like to know if the current pages response is based on a perviously sorted or searchable query, for example: on an index page running pagination, I would like to tag the `?page=3` to the sortable/searchable query string.

**Comment by jedrzej** [comment]
You mean you want to find out what currently used criteria (with/sorting/filters) are? Isn't it enough to just take whatever is in Request::all() and use that in the URL? You could also get all the information needed from the query builder that is returned from pimp() - via its getEagerLoads() (for with), $orders (for sorting) or $wheres.

I could add some static methods to the model classes, sth like Model::getFilters() that could parse the request data and return the criteria that would be applied, but it would require significant amount of work, so I'd like to see some use-cases where solutions mentioned above won't be enough. If that's just about generating URL, then Request::all() is your friend :)
