### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by dileep-costprize** [jedrzej/pimpable#9]
Is it possible to perform a global search.. i.e instead of 
GET /api/posts
  ?thread_id=42
  &text=%awesome%
  &created_at=(ge)201403
  &user_id=!666
  &sort[]=is_active,desc
  &sort[]=created_at,desc
  &with=user

can the get request be like GET /api/posts?search=%awesome%

**Comment by jedrzej** [comment]
You need to implement such a filter yourself - see example below that searches a string in model's `name` and `email` attributes:

```
protected function processTextFilter(Builder $builder, Constraint $constraint)
{
    if ($constraint->getOperator() === Constraint::OPERATOR_EQUAL) {
        $builder->where(function ($query) use ($constraint) {
            $value = sprintf('%%%s%%', trim($value, '%'));
            $query
              ->where('name', $constraint->getOperator(), $value)
              ->orWhere('email', $constraint->getOperator(), $value);
        });
    }

   return true;
}
```
